// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlQVvcr9KbQDzLa2xuo-CBRqighlEpDYg',
    appId: '1:196839440116:web:b226c5510a07d0315ae8a1',
    messagingSenderId: '196839440116',
    projectId: 'sera-198ee',
    authDomain: 'sera-198ee.firebaseapp.com',
    storageBucket: 'sera-198ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhfwt4_8ot1FHSQYVF7qZbaBaufQK58yk',
    appId: '1:196839440116:android:428dad1ea7a55fa15ae8a1',
    messagingSenderId: '196839440116',
    projectId: 'sera-198ee',
    storageBucket: 'sera-198ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8wrHBi78SomPDySFjI81UeHZOmi8lXIE',
    appId: '1:196839440116:ios:df88ebda53da5dbb5ae8a1',
    messagingSenderId: '196839440116',
    projectId: 'sera-198ee',
    storageBucket: 'sera-198ee.appspot.com',
    iosBundleId: 'com.triaxo.sera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8wrHBi78SomPDySFjI81UeHZOmi8lXIE',
    appId: '1:196839440116:ios:df88ebda53da5dbb5ae8a1',
    messagingSenderId: '196839440116',
    projectId: 'sera-198ee',
    storageBucket: 'sera-198ee.appspot.com',
    iosBundleId: 'com.triaxo.sera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlQVvcr9KbQDzLa2xuo-CBRqighlEpDYg',
    appId: '1:196839440116:web:9c68afd9c07268755ae8a1',
    messagingSenderId: '196839440116',
    projectId: 'sera-198ee',
    authDomain: 'sera-198ee.firebaseapp.com',
    storageBucket: 'sera-198ee.appspot.com',
  );
}
